{% set name = "xtl" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtl/archive/{{ version }}.tar.gz
  sha256: ee38153b7dd0ec84cee3361f5488a4e7e6ddd26392612ac8821cbc76e740273a

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/xtl/xbasic_fixed_string.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/xtl/xtlConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/xtl/xtlConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtl\xbasic_fixed_string.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtl\xtlConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtl\xtlConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The xtensor-stack tools library
  description: Basic tools (containers, algorithms) used by other packages from the xtensor and xeus stacks.
  doc_url: https://xtl.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtl

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
    - conda-forge/xtensor
