appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: W+UjgjmPS5623weJIK/KysSC2auU0/uyzfxYHez5w2NIva7irMpOBqI3qpIYpKtX45pFtKvzg2kI3EaBfAzCJ/gge+KDVW8qY8knen/0Y3VqK8opHzjqkpKrHTnDcpWwEXOvKAJpbqe/ud8cz8lXxZtH/zRUQA1r1gpwITVbO83YW2N+00Cum867aj6xH0GVcK1UFBs0kzQ8so1YO8awD5fC5AGU3yTYma08H0FOlYGB9jKNWtdjH5tQu4z8euDZ3NL32/8r7rGxFjPyJEoDuqCgZa0rwnD7cD0h5BIGDjgl/o8cm8zPc7xD+DEUVbqW8H+ezJN/xrgoQifxnfFmfuQXsuqqRtiJi7yvVxrh029oCS9p+2MyRNtxeR4vhCbyNFmkClHbzl6Ej6xpGncWdmtJ0miD/xz6Buiuz85engorhe8a91fZBA752tHEB65lH1d/ipSQhZu21q4IcRcB+/PC+3GWa5AQQifxwT+scqPo3K6oHn1Ta21EXceO/23DUQp5RGRMZANaUKC/k2GLegtzuEupJx3ntVUauFR1xm3jXog3RUJJIqncy6y7J3nUdCFVkvZvPzXiu2fQ+IwzZWUby1x5S0eXQIU4gvXwuJD7bwDbKeklRb/vzCHDG9qikNWePbLMtKud4P5wL+Q7wxy9YDsuD7Tsts1ZKg+eSV0=}
